### ISSUE TITLE
Does not work in Safari on MAC!

### ISSUE THREAD

**Issue by csillery** [thednp/jQueryTween#8]

**Comment by thednp** [comment]
First: do you have a test site?

Second: use my kute.js, it's much better

**Comment by csillery** [comment]
test site: http://thednp.github.io/jQueryTween/

**Comment by thednp** [comment]
Can you please point out steps to replicate?

**Comment by thednp** [comment]
Also, would love to see some screenshots.

**Comment by thednp** [comment]
I just checked Safari, yuck!! Such a terrible browser for Windows. Are you on a Mac? Perhaps it's different/better?

**Comment by csillery** [comment]
Yes, I'm on Mac.

**Comment by thednp** [comment]
Well, gimme some screenshots, for me it works partly on Windows, I believe there must be some graphics driver issues.

**Comment by csillery** [comment]
FYI, it works in Chrome.

**Comment by thednp** [comment]
Please gimme a list of tween properties that don't work, some screenshots, I cannot feel or guess what could be the problem, ei?

**Comment by csillery** [comment]
I'm using your demo page and none of them work.
![screensnapz017](https://cloud.githubusercontent.com/assets/636151/7731393/1e9b30e2-feee-11e4-8b0e-c38961c4426d.png)

**Comment by thednp** [comment]
Both `color` and `backgroundColor` work for me in Safari for Windows.

**Comment by csillery** [comment]
In Chrome it does the animation then the button changes text...
![screensnapz020](https://cloud.githubusercontent.com/assets/636151/7731516/fd85d082-feee-11e4-81ed-84529c792eee.png)

**Comment by thednp** [comment]
I don't own a MAC and I don't know how to debug stuff, let's start with the usual:
* do you have latest OS version, latest Safari version?
* do you have any error in browser console?

**Comment by thednp** [comment]
Quick note: after installing Firebug Lite for Safari, it seems to work quite well for me now.

**Comment by csillery** [comment]
To what are you adding the prefix to?

**Comment by thednp** [comment]
Prefix is required for all CSS3 stuff in Safari: `-webkit-perspective`, `-webkit-transition`, `-webkit-transform` and everything in between.

**Comment by csillery** [comment]
I know what the -webkit- prefix is used for but to what are you adding it to?

**Comment by thednp** [comment]
I'm adding it to the demo layers that use `transform`, in my demo is about `translate` and `rotate`.
